### ISSUE TITLE
Investigate improper autonomous

### ISSUE THREAD

**Issue by lmaxwell24** [1757WestwoodRobotics/2022-RapidReact#100]
our entire autonomous routine seems to be off as far as distances are concerned, going not as far as it should

possible idea is that we reassert our position with too much weight and the lag of nettables is biting us because of it, thinking of a spot that we were and not current are

**Comment by lmaxwell24** [comment]
also milestone:
100th PR/issue

**Comment by lmaxwell24** [comment]
@LandonBayer summary of findings?

**Comment by LandonBayer** [comment]
Most things are solved at this point (which is why we merged) but here we go:
-Vision odometry makes auto very screwy (solved by disabling for auto)
-ResetDrive works now
-Gains stolen from 6328 work pretty well in sim
-On long/complicated paths (see 4 ball) the bot can get pretty off track so we won't want to use it; however, 5 ball is consistently fine
