### ISSUE TITLE
refactor drive subsystem to be less repetative

### ISSUE THREAD

**Issue by lmaxwell24** [1757WestwoodRobotics/2022-RapidReact#46]
within `drivesubsystem.py` there is currently a lot of the same following code:
```py
if not ctreCheckError(... ... ...):
    return
```
Being copy pasted a total of 15(!) times, it makes it the singular largest repeated section in the entire code base, all with slight variations on the same few ideas. I propose a refactoring to make it less  and easier to change in the event it needs to be.

**Comment by caloisio** [comment]
Instead of the current implementation or the proposed PR, perhaps the proper design would be to change `ctreCheckError` to raise an exception rather than returning `true`/`false`. The initialization would then be neatly encapsulated in a `try/except/else/finally` block which also behaves exactly as desired for only executing subsequent commands if the previous commands succeeded (which is a requirement for hardware initialization).

**Comment by lmaxwell24** [comment]
closing from lack of activity
